name: firebase_with_riverpod
description: "A blueprint Flutter project integrating Firebase with Riverpod and
  Clean Architecture."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  arsync_firebase_errors_handler: ^0.0.3
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.3.3
  dotenv: ^4.2.0
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.4.0
  form_validator: ^2.1.1
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  get_storage: ^2.1.1
  go_router: ^14.7.1
  hooks_riverpod: ^2.5.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.16.0
  mocktail: ^1.0.4
  riverpod_annotation: ^2.1.5
  shared_preferences: ^2.5.3
  url_strategy: ^0.3.0
  validators: ^3.0.0
  very_good_analysis: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env.dev
    - .env

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/sf_fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/sf_fonts/SFProText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/sf_fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/sf_fonts/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/sf_fonts/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/sf_fonts/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/sf_fonts/SFProText-Bold.ttf
          weight: 700
        - asset: assets/sf_fonts/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/sf_fonts/SFProText-Heavy.ttf
          weight: 800
        - asset: assets/sf_fonts/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: assets/sf_fonts/SFProText-Light.ttf
          weight: 300
        - asset: assets/sf_fonts/SFProText-LightItalic.ttf
          weight: 300
          style: italic
